let barData = [
  {
    id: "magnums",
    name: "MAGNUMS",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    dining: false,
    ages: "All Ages",
    smoking: true,
    gambling: true,
    family: false,
    music: true,
    sports: true,
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },

  {
    id: "boatys",
    name: "BOATYS",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    summary: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/img-2.jpg",
  },

  {
    id: "beaches",
    name: "BEACHES",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    summary: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/img-3.jpg",
  },

  {
    id: "abh",
    name: "AIRLIE BEACH HOTEL",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    summary: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "anchor",
    name: "ANCHOR BAR",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    summary: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/img-5.jpg",
  },
];