let barData = [
  {
    id: "magnums",
    name: "MAGNUMS",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    hasPool: true,
    pool: "3 tables, $3 per game.",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },

  {
    id: "beaches",
    name: "BEACHES",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "12pm - 11pm",
    tue: "12pm - 11pm",
    wed: "12pm - 11pm",
    thur: "12pm - 11pm",
    fri: "12pm -11pm",
    sat: "12pm -11pm",
    sun: "12pm - 11pm",
    hasDining: false,
    dining: "Kitchen Open: 12pm-9pm",
    hasGambling: false,
    gambling: "N/A",
    isAges1830: true,
    ages: "Mostly 18-30",
    hasMusic: true,
    music: "Live Bands",
    hasSports: false,
    sports: "N/A",
    hasPool: true,
    pool: "3 tables, $3 per game.",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.0,
    maps: "https://goo.gl/maps/i7eak1rCBRJaPnbw8",
  },
  {
    id: "boatys",
    name: "BOATY'S",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "12pm - 12am",
    tue: "12pm - 12am",
    wed: "12pm - 12am",
    thur: "12pm - 12am",
    fri: "12pm - 2am",
    sat: "12pm - 2am",
    sun: "12pm - 12pm",
    type: "Bar",
    hasDining: true,
    dining: "12pm-9pm ",
    hasGambling: false,
    gambling: "N/A",
    isAges1830: true,
    ages: "Mostly 18-30",
    hasMusic: true,
    music: "Live Bands",
    hasSports: false,
    sports: "N/A",
    hasSmoking: true,
    smoking: "Yes",
    hasPool: false,
    pool: "N/A",
    rating: 4.5,
    maps: "https://goo.gl/maps/WMtQrzqEES6XK10pm",
  },
  {
    id: "abh",
    name: "AIRLIE BEACH HOTEL",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 10pm",
    tue: "10am - 10pm",
    wed: "10am - 10pm",
    thur: "10am - 10pm",
    fri: "10am -10pm",
    sat: "10am -10pm",
    sun: "10am - 10pm",
    type: "Bar",
    hasDining: true,
    dining: "12pm-2pm, 5pm-9pm",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno. Open until 4am.",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, greatest ever",
    hasPool: false,
    pool: "N/A",
    rating: 4.1,
    maps: "https://goo.gl/maps/mDgcMYdgGT9jFusn6",
  },
  {
    id: "anchor",
    name: "ANCHOR BAR",
    location: "ACLOSED",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "CLOSED",
    tue: "CLOSED",
    wed: "CLOSED",
    thur: "12pm-9pm",
    fri: "12pm-9pm",
    sat: "12pm-9pm",
    sun: "12pm-9pm",
    type: "Bar & Restaurant",
    hasDining: true,
    dining: "12pm-8:30pm",
    hasGambling: false,
    gambling: "N/A",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: false,
    music: "N/A",
    hasSports: false,
    sports: "N/A",
    hasSmoking: true,
    smoking: "Yes",
    hasPool: true,
    pool: "1 table, $2 per game",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "kcs",
    name: "KC'S BAR & GRILL",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "paradiso",
    name: "PARADISO",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "mika",
    name: "MIKA",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "paddys",
    name: "PADDY SHENANIGANS",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "boom",
    name: "BOOM NIGHTCLUB",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "mamas",
    name: "MAMA AFRICAS",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "hush",
    name: "HUSH BAR",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "breeze",
    name: "BREEZE BAR",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "sailing",
    name: "WHITSUNDAY SAILING CLUB",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "rocks",
    name: "THE ROCKS",
    location: "Coral Sea Marina",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },

  {
    id: "sorrentos",
    name: "SORRENTO'S",
    location: "Coral Sea Marina",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "jubes",
    name: "JUBILEE POCKET TAVERN",
    location: "Jubilee Pocket",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "banjos",
    name: "BANJOS BAR & GRILL",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "ballistic",
    name: "BALLISTIC BREWING CO.",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "rgh",
    name: "REEF GATEWAY HOTEL",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "northerlies",
    name: "NORTHERLIES",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
  {
    id: "explore",
    name: "EXPLORE 74",
    location: "Airlie Beach Main Street",
    img: "images/img-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    mon: "10am - 12am",
    tue: "10am - 12am",
    wed: "10am - 12am",
    thur: "10am - 12am",
    fri: "10am - 2am",
    sat: "10am - 2am",
    sun: "10am - 12pm",
    type: "Bar",
    hasDining: false,
    dining: "N/A",
    hasGambling: true,
    gambling: "TAB, Pokies & Keno",
    isAllAges: true,
    ages: "All Ages",
    hasMusic: true,
    music: "Live Bands",
    hasSports: true,
    sports: "Shows sports",
    hasSmoking: true,
    smoking: "Yes, many",
    rating: 4.5,
    maps: "https://goo.gl/maps/X6niqrstYaz69D9C6",
  },
];
